--- 
- name: Launch ubuntu instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ region }}"
        security_groups: "{{ security_group }}"
        wait: yes
        count: 1
        network:
          assign_public_ip: true
        tags:
          Environment: Dev
      register: ec2

    - name: Print public IP
      debug: 
        msg: "Public IP: {{ec2.instances[0].public_ip_address}}"