---
- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - vars.yml
  roles:
    - create_instance

- name: Wait for EC2 instance SSH to be ready
  hosts: launched
  tasks:
    - name: Wait for SSH
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 300

- name: Configure EC2 frontend
  hosts: launched
  become: yes
  roles:
    - frontend

- name: Configure EC2 backend
  hosts: launched
  become: yes
  roles:
    - backend
